# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1110467fbbf7a353d2ec9a3dfa6e86d595f2363a0e4c16955b83092336cffcc12be17c9fb69e2cd9b362ec469d904835456008b7d5637094a59e49659c26d534

test:
  secret_key_base: 42bace5429cde172ea827517eb5c6bbf76c0406a3ce0dbd3cff4b1707c49d7c7c1b4e405638950196a8dedb0745cd35a959271dc186c25a1a928f054fca69e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
