User.create!([
  {validated: false, email: "dom0308@gmail.com", encrypted_password: "$2a$10$EscKDU622RQHrC4W7LSSX.DuZC4WtUYPzsPjToeNAxzFRH.fkvKBy", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 17, current_sign_in_at: "2016-05-12 15:32:54", last_sign_in_at: "2016-05-12 12:46:08", current_sign_in_ip: "::1", last_sign_in_ip: "::1", confirmation_token: "2xwCxKrHNKg-CFDxyQMo", confirmed_at: "2016-04-14 12:01:07", confirmation_sent_at: "2016-04-14 11:59:15", unconfirmed_email: nil, failed_attempts: 0, locked_at: nil, deleted: false}
])
Admin.create!([
  {email: "dom0308@gmail.com", encrypted_password: "$2a$10$p2DSQgQ4tQ2QDInPKyC13uKyYgyRKspjc2sNuECqrIrFkSkwyf3Li", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 1, current_sign_in_at: "2016-04-14 11:56:34", last_sign_in_at: "2016-04-14 11:56:34", current_sign_in_ip: "::1", last_sign_in_ip: "::1", failed_attempts: 0, locked_at: nil},
  {email: "plut.car@gmail.com", encrypted_password: "$2a$10$dorwQns/Qt59u5.P/22tUupt9ZRaYuMwWwbgekJdGKMEG.X76b6Ji", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, failed_attempts: 0, locked_at: nil}
])
Doctor.create!([
  {doctorNumber: "e12348", category: "zobozdravnik", lastName: "Novak", firstName: "Janez", phone: "041-111-111", limitPatient: 40, hospital_id: nil, email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, failed_attempts: 0, locked_at: nil, deleted: false},
  {doctorNumber: "e10789", category: "ortodont", lastName: "MIha", firstName: "Kovac", phone: "041-222-222", limitPatient: 30, hospital_id: nil, email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, failed_attempts: 0, locked_at: nil, deleted: false},
  {doctorNumber: "e123", category: "zobozdravnik", lastName: "Novak", firstName: "Janez", phone: "041222222", limitPatient: 40, hospital_id: nil, email: "janez.nov@gmail.com", encrypted_password: "$2a$10$WMeNUJmlHjbxAjw.Y1nkZu7Pw0DnRRXzXKhsbO.U8S99afYBwajqa", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 3, current_sign_in_at: "2016-05-12 12:16:11", last_sign_in_at: "2016-05-12 12:13:27", current_sign_in_ip: "::1", last_sign_in_ip: "::1", failed_attempts: 0, locked_at: nil, deleted: true},
  {doctorNumber: nil, category: nil, lastName: nil, firstName: nil, phone: nil, limitPatient: nil, hospital_id: 2, email: "dom0308@gmail.co", encrypted_password: "$2a$10$SxlYn7bh4x30PLrVC5jcEe4JUNT/3QaIi3bMyyIOh0/hknxkA2tSK", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, failed_attempts: 0, locked_at: nil, deleted: true},
  {doctorNumber: "e964", category: "zobozdravnik", lastName: "Novak", firstName: "Bine", phone: "041222222", limitPatient: 40, hospital_id: 1, email: "bine.novak@gmail.com", encrypted_password: "$2a$10$L/ufp206mryBejZMCQd/WecwP9HU35aUOZGhuXOpsPRI596F2vB3y", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 4, current_sign_in_at: "2016-05-12 12:29:18", last_sign_in_at: "2016-05-12 12:11:10", current_sign_in_ip: "::1", last_sign_in_ip: "::1", failed_attempts: 0, locked_at: nil, deleted: false},
  {doctorNumber: "e789", category: "zdravnik", lastName: "Plut", firstName: "Miha", phone: "041123789", limitPatient: 30, hospital_id: 1, email: "miha.kov@gmail.com", encrypted_password: "$2a$10$QTuNnZ3strK85IpiNOVe0uXeX8KkNysrrJ/688g9swcPZT3afC54u", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, failed_attempts: 0, locked_at: nil, deleted: true}
])
Nurse.create!([
  {nurseNumber: "n1205", lastName: "Spela", firstName: "Pregelj", phone: "041-333-333", hospital_id: nil, email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, failed_attempts: 0, locked_at: nil, deleted: false},
  {nurseNumber: "m123", lastName: "Rogelj", firstName: "Nina", phone: "041555555", hospital_id: 1, email: "medicinska@gmail.com", encrypted_password: "$2a$10$knx3Tmnkf.2SheWt4IzG3.KoNF7DJSk0/ulddYXhoz4ZRoNVhwkwa", reset_password_token: nil, reset_password_sent_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, failed_attempts: 0, locked_at: nil, deleted: false}
])
Address.create!([
  {streetName: "Hrib nad Ribcami", streetNumber: "3", post_id: 1},
  {streetName: "Hrib nad Ribcami", streetNumber: "3", post_id: 1},
  {streetName: "", streetNumber: "", post_id: nil},
  {streetName: "Sestova ulica", streetNumber: "10", post_id: 1},
  {streetName: "Ulica Staneta Bokala", streetNumber: "4", post_id: 2},
  {streetName: "Ostrovrharjeva ulica", streetNumber: "6", post_id: 3},
  {streetName: "Polje", streetNumber: "40", post_id: 4},
  {streetName: "Notranjska cesta", streetNumber: "2", post_id: 5},
  {streetName: "Licarjeva", streetNumber: "5", post_id: 6},
  {streetName: "Roska cesta", streetNumber: "18", post_id: 7},
  {streetName: "Potrceva cesta", streetNumber: "23", post_id: 8},
  {streetName: "Vodnikova cesta", streetNumber: "1", post_id: 9},
  {streetName: "Tovarniska cesta", streetNumber: "3", post_id: 10}
])
Appointment.create!([
  {date: "2011-04-10 18:00:00", check_up_id: 1, doctor_id: 1, patient_id: 1, instruction: "Upostevajte dieto za sladkorne bolnike znavodili 2, ce pride do bolecin v predelu trebuha.", duration: nil},
  {date: "2016-12-10 18:00:00", check_up_id: nil, doctor_id: 1, patient_id: 1, instruction: nil, duration: nil},
  {date: "2016-09-10 18:00:00", check_up_id: nil, doctor_id: 1, patient_id: 1, instruction: nil, duration: nil}
])
CheckUp.create!([
  {date: "2016-04-06", doctor_id: 2, patient_id: 1},
  {date: "2011-04-06", doctor_id: nil, patient_id: nil},
  {date: "2016-04-14", doctor_id: 1, patient_id: 2}
])
ContactPerson.create!([
  {lastName: "", firstName: "", phone: "", relationship: "", patient_id: 2, address_id: 3}
])
Diet.create!([
  {dietNumber: "D001", name: "Dieta pri celiakiji", deleted: false},
  {dietNumber: "D003", name: "Dieta pri refluksni bolezni", deleted: false},
  {dietNumber: "D004", name: "Dieta za sladkorne bolnike", deleted: false}
])
DietCheck.create!([
  {diet_id: 3, check_up_id: 1}
])
DietInstruction.create!([
  {diet_id: 1, deleted: false, url_string: "http://www.drustvo-celiakija.si/celiakija"},
  {diet_id: 2, deleted: false, url_string: "http://www.kclj.si/dokumenti/000203-0002f9.pdf"},
  {diet_id: 3, deleted: false, url_string: "http://www.diabetes-zveza.si/uploads/SB95_julij12clanki1.pdf"},
  {diet_id: 3, deleted: false, url_string: "http://www.ezdravje.com/srce-in-zilje/druge-bolezni-srca-in-zilja/sladkorna-bolezen/?s=9"},
  {diet_id: 3, deleted: false, url_string: "http://www.sladkorcki.si/media/docs/Prehrana_pri_SB.pdf"}
])
DoctorHasNurse.create!([
  {doctor_id: 1, nurse_id: 1},
  {doctor_id: 6, nurse_id: 2}
])
DoctorHasPatient.create!([
  {doctor_id: 5, patient_id: 1},
  {doctor_id: 6, patient_id: 1}
])
Hospital.create!([
  {hospitalNumber: "50078", hospitalName: "UKC LJUBLJANA  PEDIATRICNA  KLINIKA", address_id: nil, deleted: false},
  {hospitalNumber: nil, hospitalName: nil, address_id: nil, deleted: false},
  {hospitalNumber: nil, hospitalName: nil, address_id: nil, deleted: false},
  {hospitalNumber: nil, hospitalName: nil, address_id: nil, deleted: false}
])
Illness.create!([
  {illnessNumber: "E11", name: "Diabetes tip 2", isAllergy: false, deleted: false},
  {illnessNumber: "A01", name: "Alergija na cvetni prah", isAllergy: true, deleted: false},
  {illnessNumber: "I11", name: "Hipertenzivna srcna bolezen z (zastojno) srcno odpovedjo", isAllergy: false, deleted: false},
  {illnessNumber: "A02", name: "Alergija na glukozo", isAllergy: true, deleted: false}
])
IllnessCheck.create!([
  {illness_id: 1, check_up_id: 1},
  {illness_id: 2, check_up_id: 1},
  {illness_id: 3, check_up_id: 1},
  {illness_id: 4, check_up_id: 1}
])
Measurement.create!([
  {date: "2016-04-06 00:00:00", deleted: false},
  {date: "2016-04-03 00:00:00", deleted: false},
  {date: "2016-03-03 00:00:00", deleted: false},
  {date: "2016-01-05 17:00:00", deleted: false},
  {date: "2016-01-06 17:00:00", deleted: false},
  {date: "2016-01-07 17:00:00", deleted: false},
  {date: "2016-01-08 17:00:00", deleted: false},
  {date: "2016-01-09 17:00:00", deleted: false},
  {date: "2016-01-10 17:00:00", deleted: false},
  {date: "2016-01-11 17:00:00", deleted: false},
  {date: "2016-01-12 17:00:00", deleted: false},
  {date: "2016-01-13 17:00:00", deleted: false},
  {date: "2016-01-14 17:00:00", deleted: false},
  {date: "2016-01-15 17:00:00", deleted: false},
  {date: "2016-01-16 17:00:00", deleted: false},
  {date: "2016-01-17 17:00:00", deleted: false},
  {date: "2016-01-18 17:00:00", deleted: false},
  {date: "2016-01-19 17:00:00", deleted: false},
  {date: "2016-01-20 17:00:00", deleted: false},
  {date: "2016-01-21 17:00:00", deleted: false},
  {date: "2016-01-22 17:00:00", deleted: false},
  {date: "2016-01-23 17:00:00", deleted: false},
  {date: "2016-01-24 17:00:00", deleted: false},
  {date: "2016-01-25 17:00:00", deleted: false},
  {date: "2016-01-26 17:00:00", deleted: false},
  {date: "2016-01-27 17:00:00", deleted: false},
  {date: "2016-01-28 17:00:00", deleted: false},
  {date: "2016-01-29 17:00:00", deleted: false},
  {date: "2016-01-30 17:00:00", deleted: false},
  {date: "2016-01-31 17:00:00", deleted: false},
  {date: "2016-02-01 17:00:00", deleted: false},
  {date: "2016-02-02 17:00:00", deleted: false},
  {date: "2016-02-03 17:00:00", deleted: false},
  {date: "2016-02-04 17:00:00", deleted: false},
  {date: "2016-02-05 17:00:00", deleted: false},
  {date: "2016-02-06 17:00:00", deleted: false},
  {date: "2016-02-07 17:00:00", deleted: false},
  {date: "2016-02-08 17:00:00", deleted: false},
  {date: "2016-02-09 17:00:00", deleted: false},
  {date: "2016-02-10 17:00:00", deleted: false},
  {date: "2016-02-11 17:00:00", deleted: false},
  {date: "2016-02-12 17:00:00", deleted: false},
  {date: "2016-02-13 17:00:00", deleted: false},
  {date: "2016-02-14 17:00:00", deleted: false},
  {date: "2016-02-15 17:00:00", deleted: false},
  {date: "2016-02-16 17:00:00", deleted: false},
  {date: "2016-02-17 17:00:00", deleted: false},
  {date: "2016-02-18 17:00:00", deleted: false},
  {date: "2016-02-19 17:00:00", deleted: false},
  {date: "2016-02-20 17:00:00", deleted: false},
  {date: "2016-02-21 17:00:00", deleted: false},
  {date: "2016-02-22 17:00:00", deleted: false},
  {date: "2016-02-23 17:00:00", deleted: false},
  {date: "2016-02-24 17:00:00", deleted: false},
  {date: "2016-02-25 17:00:00", deleted: false},
  {date: "2016-02-26 17:00:00", deleted: false},
  {date: "2016-02-27 17:00:00", deleted: false},
  {date: "2016-02-28 17:00:00", deleted: false},
  {date: "2016-02-29 17:00:00", deleted: false},
  {date: "2016-03-01 17:00:00", deleted: false},
  {date: "2016-03-02 17:00:00", deleted: false},
  {date: "2016-03-03 17:00:00", deleted: false},
  {date: "2016-03-04 17:00:00", deleted: false},
  {date: "2016-03-05 17:00:00", deleted: false},
  {date: "2016-03-06 17:00:00", deleted: false},
  {date: "2016-03-07 17:00:00", deleted: false},
  {date: "2016-03-08 17:00:00", deleted: false},
  {date: "2016-03-09 17:00:00", deleted: false},
  {date: "2016-03-10 17:00:00", deleted: false},
  {date: "2016-03-11 17:00:00", deleted: false},
  {date: "2016-03-12 17:00:00", deleted: false},
  {date: "2016-03-13 17:00:00", deleted: false},
  {date: "2016-03-14 17:00:00", deleted: false},
  {date: "2016-03-15 17:00:00", deleted: false},
  {date: "2016-03-16 17:00:00", deleted: false},
  {date: "2016-03-17 17:00:00", deleted: false},
  {date: "2016-03-18 17:00:00", deleted: false},
  {date: "2016-03-19 17:00:00", deleted: false},
  {date: "2016-03-20 17:00:00", deleted: false},
  {date: "2016-03-21 17:00:00", deleted: false},
  {date: "2016-03-22 17:00:00", deleted: false},
  {date: "2016-03-23 17:00:00", deleted: false},
  {date: "2016-03-24 17:00:00", deleted: false},
  {date: "2016-03-25 17:00:00", deleted: false},
  {date: "2016-03-26 17:00:00", deleted: false},
  {date: "2016-03-27 16:00:00", deleted: false},
  {date: "2016-03-28 16:00:00", deleted: false},
  {date: "2016-03-29 16:00:00", deleted: false},
  {date: "2016-03-30 16:00:00", deleted: false},
  {date: "2016-03-31 16:00:00", deleted: false},
  {date: "2016-04-01 16:00:00", deleted: false},
  {date: "2016-04-02 16:00:00", deleted: false},
  {date: "2016-04-03 16:00:00", deleted: false},
  {date: "2016-04-04 16:00:00", deleted: false},
  {date: "2016-04-05 16:00:00", deleted: false},
  {date: "2016-04-06 16:00:00", deleted: false},
  {date: "2016-04-07 16:00:00", deleted: false},
  {date: "2016-04-08 16:00:00", deleted: false},
  {date: "2016-04-09 16:00:00", deleted: false}
])
MeasurementDoc.create!([
  {check_up_id: 1, part_measurement_id: 11, deleted: false},
  {check_up_id: 1, part_measurement_id: 12, deleted: false}
])
MeasurementHome.create!([
  {patient_id: 1, part_measurement_id: 1, deleted: false},
  {patient_id: 1, part_measurement_id: 2, deleted: false},
  {patient_id: 1, part_measurement_id: 3, deleted: false},
  {patient_id: 1, part_measurement_id: 4, deleted: false},
  {patient_id: 1, part_measurement_id: 5, deleted: false},
  {patient_id: 1, part_measurement_id: 6, deleted: false},
  {patient_id: 1, part_measurement_id: 7, deleted: false},
  {patient_id: 1, part_measurement_id: 8, deleted: false},
  {patient_id: 1, part_measurement_id: 9, deleted: false},
  {patient_id: 1, part_measurement_id: 10, deleted: false},
  {patient_id: 1, part_measurement_id: 14, deleted: false},
  {patient_id: 1, part_measurement_id: 15, deleted: false},
  {patient_id: 1, part_measurement_id: 16, deleted: false},
  {patient_id: 1, part_measurement_id: 17, deleted: false},
  {patient_id: 1, part_measurement_id: 18, deleted: false},
  {patient_id: 1, part_measurement_id: 19, deleted: false},
  {patient_id: 1, part_measurement_id: 20, deleted: false},
  {patient_id: 1, part_measurement_id: 21, deleted: false},
  {patient_id: 1, part_measurement_id: 22, deleted: false},
  {patient_id: 1, part_measurement_id: 23, deleted: false},
  {patient_id: 1, part_measurement_id: 24, deleted: false},
  {patient_id: 1, part_measurement_id: 25, deleted: false},
  {patient_id: 1, part_measurement_id: 26, deleted: false},
  {patient_id: 1, part_measurement_id: 27, deleted: false},
  {patient_id: 1, part_measurement_id: 28, deleted: false},
  {patient_id: 1, part_measurement_id: 29, deleted: false},
  {patient_id: 1, part_measurement_id: 30, deleted: false},
  {patient_id: 1, part_measurement_id: 31, deleted: false},
  {patient_id: 1, part_measurement_id: 32, deleted: false},
  {patient_id: 1, part_measurement_id: 33, deleted: false},
  {patient_id: 1, part_measurement_id: 34, deleted: false},
  {patient_id: 1, part_measurement_id: 35, deleted: false},
  {patient_id: 1, part_measurement_id: 36, deleted: false},
  {patient_id: 1, part_measurement_id: 37, deleted: false},
  {patient_id: 1, part_measurement_id: 38, deleted: false},
  {patient_id: 1, part_measurement_id: 39, deleted: false},
  {patient_id: 1, part_measurement_id: 40, deleted: false},
  {patient_id: 1, part_measurement_id: 41, deleted: false},
  {patient_id: 1, part_measurement_id: 42, deleted: false},
  {patient_id: 1, part_measurement_id: 43, deleted: false},
  {patient_id: 1, part_measurement_id: 44, deleted: false},
  {patient_id: 1, part_measurement_id: 45, deleted: false},
  {patient_id: 1, part_measurement_id: 46, deleted: false},
  {patient_id: 1, part_measurement_id: 47, deleted: false},
  {patient_id: 1, part_measurement_id: 48, deleted: false},
  {patient_id: 1, part_measurement_id: 49, deleted: false},
  {patient_id: 1, part_measurement_id: 50, deleted: false},
  {patient_id: 1, part_measurement_id: 51, deleted: false},
  {patient_id: 1, part_measurement_id: 52, deleted: false},
  {patient_id: 1, part_measurement_id: 53, deleted: false},
  {patient_id: 1, part_measurement_id: 54, deleted: false},
  {patient_id: 1, part_measurement_id: 55, deleted: false},
  {patient_id: 1, part_measurement_id: 56, deleted: false},
  {patient_id: 1, part_measurement_id: 57, deleted: false},
  {patient_id: 1, part_measurement_id: 58, deleted: false},
  {patient_id: 1, part_measurement_id: 59, deleted: false},
  {patient_id: 1, part_measurement_id: 60, deleted: false},
  {patient_id: 1, part_measurement_id: 61, deleted: false},
  {patient_id: 1, part_measurement_id: 62, deleted: false},
  {patient_id: 1, part_measurement_id: 63, deleted: false},
  {patient_id: 1, part_measurement_id: 64, deleted: false},
  {patient_id: 1, part_measurement_id: 65, deleted: false},
  {patient_id: 1, part_measurement_id: 66, deleted: false},
  {patient_id: 1, part_measurement_id: 67, deleted: false},
  {patient_id: 1, part_measurement_id: 68, deleted: false},
  {patient_id: 1, part_measurement_id: 69, deleted: false},
  {patient_id: 1, part_measurement_id: 70, deleted: false},
  {patient_id: 1, part_measurement_id: 71, deleted: false},
  {patient_id: 1, part_measurement_id: 72, deleted: false},
  {patient_id: 1, part_measurement_id: 73, deleted: false},
  {patient_id: 1, part_measurement_id: 74, deleted: false},
  {patient_id: 1, part_measurement_id: 75, deleted: false},
  {patient_id: 1, part_measurement_id: 76, deleted: false},
  {patient_id: 1, part_measurement_id: 77, deleted: false},
  {patient_id: 1, part_measurement_id: 78, deleted: false},
  {patient_id: 1, part_measurement_id: 79, deleted: false},
  {patient_id: 1, part_measurement_id: 80, deleted: false},
  {patient_id: 1, part_measurement_id: 81, deleted: false},
  {patient_id: 1, part_measurement_id: 82, deleted: false},
  {patient_id: 1, part_measurement_id: 83, deleted: false},
  {patient_id: 1, part_measurement_id: 84, deleted: false},
  {patient_id: 1, part_measurement_id: 85, deleted: false},
  {patient_id: 1, part_measurement_id: 86, deleted: false},
  {patient_id: 1, part_measurement_id: 87, deleted: false},
  {patient_id: 1, part_measurement_id: 88, deleted: false},
  {patient_id: 1, part_measurement_id: 89, deleted: false},
  {patient_id: 1, part_measurement_id: 90, deleted: false},
  {patient_id: 1, part_measurement_id: 91, deleted: false},
  {patient_id: 1, part_measurement_id: 92, deleted: false},
  {patient_id: 1, part_measurement_id: 93, deleted: false},
  {patient_id: 1, part_measurement_id: 94, deleted: false},
  {patient_id: 1, part_measurement_id: 95, deleted: false},
  {patient_id: 1, part_measurement_id: 96, deleted: false},
  {patient_id: 1, part_measurement_id: 97, deleted: false},
  {patient_id: 1, part_measurement_id: 98, deleted: false},
  {patient_id: 1, part_measurement_id: 99, deleted: false},
  {patient_id: 1, part_measurement_id: 100, deleted: false},
  {patient_id: 1, part_measurement_id: 101, deleted: false},
  {patient_id: 1, part_measurement_id: 102, deleted: false},
  {patient_id: 1, part_measurement_id: 103, deleted: false},
  {patient_id: 1, part_measurement_id: 104, deleted: false},
  {patient_id: 1, part_measurement_id: 105, deleted: false},
  {patient_id: 1, part_measurement_id: 106, deleted: false},
  {patient_id: 1, part_measurement_id: 107, deleted: false},
  {patient_id: 1, part_measurement_id: 108, deleted: false},
  {patient_id: 1, part_measurement_id: 109, deleted: false},
  {patient_id: 1, part_measurement_id: 110, deleted: false},
  {patient_id: 1, part_measurement_id: 111, deleted: false},
  {patient_id: 1, part_measurement_id: 112, deleted: false},
  {patient_id: 1, part_measurement_id: 113, deleted: false},
  {patient_id: 1, part_measurement_id: 114, deleted: false},
  {patient_id: 1, part_measurement_id: 115, deleted: false},
  {patient_id: 1, part_measurement_id: 116, deleted: false},
  {patient_id: 1, part_measurement_id: 117, deleted: false},
  {patient_id: 1, part_measurement_id: 118, deleted: false},
  {patient_id: 1, part_measurement_id: 119, deleted: false},
  {patient_id: 1, part_measurement_id: 120, deleted: false},
  {patient_id: 1, part_measurement_id: 121, deleted: false},
  {patient_id: 1, part_measurement_id: 122, deleted: false},
  {patient_id: 1, part_measurement_id: 123, deleted: false},
  {patient_id: 1, part_measurement_id: 124, deleted: false},
  {patient_id: 1, part_measurement_id: 125, deleted: false},
  {patient_id: 1, part_measurement_id: 126, deleted: false},
  {patient_id: 1, part_measurement_id: 127, deleted: false},
  {patient_id: 1, part_measurement_id: 128, deleted: false},
  {patient_id: 1, part_measurement_id: 129, deleted: false},
  {patient_id: 1, part_measurement_id: 130, deleted: false},
  {patient_id: 1, part_measurement_id: 131, deleted: false},
  {patient_id: 1, part_measurement_id: 132, deleted: false},
  {patient_id: 1, part_measurement_id: 133, deleted: false},
  {patient_id: 1, part_measurement_id: 134, deleted: false},
  {patient_id: 1, part_measurement_id: 135, deleted: false},
  {patient_id: 1, part_measurement_id: 136, deleted: false},
  {patient_id: 1, part_measurement_id: 137, deleted: false},
  {patient_id: 1, part_measurement_id: 138, deleted: false},
  {patient_id: 1, part_measurement_id: 139, deleted: false},
  {patient_id: 1, part_measurement_id: 140, deleted: false},
  {patient_id: 1, part_measurement_id: 141, deleted: false},
  {patient_id: 1, part_measurement_id: 142, deleted: false},
  {patient_id: 1, part_measurement_id: 143, deleted: false},
  {patient_id: 1, part_measurement_id: 144, deleted: false},
  {patient_id: 1, part_measurement_id: 145, deleted: false},
  {patient_id: 1, part_measurement_id: 146, deleted: false},
  {patient_id: 1, part_measurement_id: 147, deleted: false},
  {patient_id: 1, part_measurement_id: 148, deleted: false},
  {patient_id: 1, part_measurement_id: 149, deleted: false},
  {patient_id: 1, part_measurement_id: 150, deleted: false},
  {patient_id: 1, part_measurement_id: 151, deleted: false},
  {patient_id: 1, part_measurement_id: 152, deleted: false},
  {patient_id: 1, part_measurement_id: 153, deleted: false},
  {patient_id: 1, part_measurement_id: 154, deleted: false},
  {patient_id: 1, part_measurement_id: 155, deleted: false},
  {patient_id: 1, part_measurement_id: 156, deleted: false},
  {patient_id: 1, part_measurement_id: 157, deleted: false},
  {patient_id: 1, part_measurement_id: 158, deleted: false},
  {patient_id: 1, part_measurement_id: 159, deleted: false},
  {patient_id: 1, part_measurement_id: 160, deleted: false},
  {patient_id: 1, part_measurement_id: 161, deleted: false},
  {patient_id: 1, part_measurement_id: 162, deleted: false},
  {patient_id: 1, part_measurement_id: 163, deleted: false},
  {patient_id: 1, part_measurement_id: 164, deleted: false},
  {patient_id: 1, part_measurement_id: 165, deleted: false},
  {patient_id: 1, part_measurement_id: 166, deleted: false},
  {patient_id: 1, part_measurement_id: 167, deleted: false},
  {patient_id: 1, part_measurement_id: 168, deleted: false},
  {patient_id: 1, part_measurement_id: 169, deleted: false},
  {patient_id: 1, part_measurement_id: 170, deleted: false},
  {patient_id: 1, part_measurement_id: 171, deleted: false},
  {patient_id: 1, part_measurement_id: 172, deleted: false},
  {patient_id: 1, part_measurement_id: 173, deleted: false},
  {patient_id: 1, part_measurement_id: 174, deleted: false},
  {patient_id: 1, part_measurement_id: 175, deleted: false},
  {patient_id: 1, part_measurement_id: 176, deleted: false},
  {patient_id: 1, part_measurement_id: 177, deleted: false},
  {patient_id: 1, part_measurement_id: 178, deleted: false},
  {patient_id: 1, part_measurement_id: 179, deleted: false},
  {patient_id: 1, part_measurement_id: 180, deleted: false},
  {patient_id: 1, part_measurement_id: 181, deleted: false},
  {patient_id: 1, part_measurement_id: 182, deleted: false},
  {patient_id: 1, part_measurement_id: 183, deleted: false},
  {patient_id: 1, part_measurement_id: 184, deleted: false},
  {patient_id: 1, part_measurement_id: 185, deleted: false},
  {patient_id: 1, part_measurement_id: 186, deleted: false},
  {patient_id: 1, part_measurement_id: 187, deleted: false},
  {patient_id: 1, part_measurement_id: 188, deleted: false},
  {patient_id: 1, part_measurement_id: 189, deleted: false},
  {patient_id: 1, part_measurement_id: 190, deleted: false},
  {patient_id: 1, part_measurement_id: 191, deleted: false},
  {patient_id: 1, part_measurement_id: 192, deleted: false},
  {patient_id: 1, part_measurement_id: 193, deleted: false},
  {patient_id: 1, part_measurement_id: 194, deleted: false},
  {patient_id: 1, part_measurement_id: 195, deleted: false},
  {patient_id: 1, part_measurement_id: 196, deleted: false},
  {patient_id: 1, part_measurement_id: 197, deleted: false}
])
Medicine.create!([
  {medicineNumber: "082392", name: "Enalapril Vitabalans 10 mg tbl", inUse: true, medicine_instruction_id: 1},
  {medicineNumber: "016470", name: "Piramil 10 mg tbl", inUse: true, medicine_instruction_id: 2},
  {medicineNumber: "115746", name: "Byol 5 mg tbl", inUse: nil, medicine_instruction_id: 3},
  {medicineNumber: "129607", name: "Borez 5 mg tbl", inUse: nil, medicine_instruction_id: 4},
  {medicineNumber: "146097", name: "Concordina 5 mg/5 mg tbl", inUse: nil, medicine_instruction_id: 5},
  {medicineNumber: "060755", name: "Lodoz 5 mg/6,25 mg tbl", inUse: nil, medicine_instruction_id: 6},
  {medicineNumber: "146144", name: "Sobycor 5 mg tbl", inUse: nil, medicine_instruction_id: 7},
  {medicineNumber: "144343", name: "Aglurab 1000 mg tbl", inUse: nil, medicine_instruction_id: 8},
  {medicineNumber: "040886", name: "Glucophage 1000 mg tbl", inUse: nil, medicine_instruction_id: 9},
  {medicineNumber: "145137", name: "Belformin 500 mg tbl", inUse: nil, medicine_instruction_id: 10},
  {medicineNumber: "108375", name: "Formagliben 500 mg/2,5 mg tbl", inUse: nil, medicine_instruction_id: 11},
  {medicineNumber: "040886", name: "Glucophage 1000 mg tbl", inUse: nil, medicine_instruction_id: 12},
  {medicineNumber: "042021", name: "Metfogamma 1000 mg tbl", inUse: nil, medicine_instruction_id: 13},
  {medicineNumber: "025550", name: "Siofor 1000 mg tbl", inUse: nil, medicine_instruction_id: 14},
  {medicineNumber: "030619", name: "Actrapid 100 i.e. Raztopina za injiciranje v viali", inUse: nil, medicine_instruction_id: 15},
  {medicineNumber: "051101", name: "Actrapid FlexPen 100 i.e. Raztopina za injiciranje v napolnjenem injekcijskem peresniku", inUse: nil, medicine_instruction_id: 16},
  {medicineNumber: "095990", name: "Humulin M3 100 i.e./ml suspenzija za injiciranje v vlozku", inUse: nil, medicine_instruction_id: 17},
  {medicineNumber: "030147", name: "Insuman Rapid 100 i.e./ml OptiSet raztopina za injiciranje", inUse: nil, medicine_instruction_id: 18},
  {medicineNumber: "019534", name: "Mixtard 10 NovoLet 100 i.e./ml suspenzija za injiciranje v napolnjenem injekcijskem peresniku", inUse: nil, medicine_instruction_id: 19},
  {medicineNumber: "145976", name: "Ranitidin Accord 150 mg tbl", inUse: nil, medicine_instruction_id: 20},
  {medicineNumber: "071684", name: "Ranital 150 mg tbl", inUse: nil, medicine_instruction_id: 21},
  {medicineNumber: "146311", name: "Metamizol STADA 500 mg/ml peroralne kapljice, raztopina", inUse: nil, medicine_instruction_id: 22},
  {medicineNumber: "000191", name: "Analgin 500 mg tbl", inUse: nil, medicine_instruction_id: 23},
  {medicineNumber: "038695", name: "Omnic Ocas 0,4 mg tbl", inUse: nil, medicine_instruction_id: 24},
  {medicineNumber: "105864", name: "Combodart 0,5 mg/0,4mg kaps", inUse: nil, medicine_instruction_id: 25},
  {medicineNumber: "128333", name: "Miktan 0,4 mg tbl", inUse: nil, medicine_instruction_id: 26},
  {medicineNumber: "033880", name: "Morvesin 0,4 mg trde kapsule", inUse: nil, medicine_instruction_id: 27},
  {medicineNumber: "038245", name: "Tanyz 0,4 mg trde kapsule", inUse: nil, medicine_instruction_id: 28},
  {medicineNumber: "146102", name: "Dicitirox 50 mg tbl", inUse: nil, medicine_instruction_id: 29},
  {medicineNumber: "092010", name: "Eltroxin 50 mg tbl", inUse: nil, medicine_instruction_id: 30},
  {medicineNumber: "023442", name: "Euthyrox 50 mg tbl", inUse: nil, medicine_instruction_id: 31},
  {medicineNumber: "022454", name: "Ciprobay 500 mg tbl", inUse: nil, medicine_instruction_id: 32},
  {medicineNumber: "040398", name: "Ciprinol 500 mg tbl", inUse: nil, medicine_instruction_id: 33},
  {medicineNumber: "086029", name: "Ciprofloksacin Lek 500 mg tbl", inUse: nil, medicine_instruction_id: 34},
  {medicineNumber: "069418", name: "Primotren 80mg/ 400 mg tbl", inUse: nil, medicine_instruction_id: 35},
  {medicineNumber: "104426", name: "Coupet 20 mg tbl", inUse: nil, medicine_instruction_id: 36},
  {medicineNumber: "109827", name: "Sorvasta 20 mg tbl", inUse: nil, medicine_instruction_id: 37},
  {medicineNumber: "109932", name: "Vosustat 20 mg tbl", inUse: nil, medicine_instruction_id: 38},
  {medicineNumber: "109690", name: "Rosuvastatin Teva 20 mg tbl", inUse: nil, medicine_instruction_id: 39},
  {medicineNumber: "034487", name: "Daleron 500 mg tbl", inUse: nil, medicine_instruction_id: 40},
  {medicineNumber: "055654", name: "Lekadol 500 mg tbl", inUse: nil, medicine_instruction_id: 41},
  {medicineNumber: "002739", name: "Calpol 250 mg/5 ml peroralna suspenzija", inUse: nil, medicine_instruction_id: 42},
  {medicineNumber: "072940", name: "Doreta 37,5 mg/325 mg", inUse: nil, medicine_instruction_id: 43},
  {medicineNumber: "146066", name: "Ibuem 250 mg/250 mg/50 mg tbl", inUse: nil, medicine_instruction_id: 44},
  {medicineNumber: "093351", name: "Panadol 500 mg tbl", inUse: nil, medicine_instruction_id: 45},
  {medicineNumber: "600695", name: "Paracetamol svecke 500 mg(Lekarne Ljubljana)", inUse: nil, medicine_instruction_id: 46},
  {medicineNumber: "136058", name: "Tevitamol 500 mg tablete", inUse: nil, medicine_instruction_id: 47},
  {medicineNumber: "046124", name: "Lexaurin 3 mg tbl", inUse: nil, medicine_instruction_id: 48},
  {medicineNumber: "045136", name: "Lekotam 3 mg tbl", inUse: nil, medicine_instruction_id: 49},
  {medicineNumber: "019348", name: "Apaurin 10 mg tbl", inUse: nil, medicine_instruction_id: 50},
  {medicineNumber: "040096", name: "Cipralex 10 mg", inUse: nil, medicine_instruction_id: 51},
  {medicineNumber: "125610", name: "Citafort 10 mg tbl", inUse: nil, medicine_instruction_id: 52},
  {medicineNumber: "058793", name: "Ecytara 10 mg tbl", inUse: nil, medicine_instruction_id: 53},
  {medicineNumber: "085685", name: "Elicea 10 mg tbl", inUse: nil, medicine_instruction_id: 54},
  {medicineNumber: "146299", name: "Escitalopram Krka 10 mg tbl", inUse: nil, medicine_instruction_id: 55},
  {medicineNumber: "118460", name: "Otigem 10 mg tbl", inUse: nil, medicine_instruction_id: 56},
  {medicineNumber: "104213", name: "Solatcit 10 mg tbl", inUse: nil, medicine_instruction_id: 57},
  {medicineNumber: "072940", name: "Doreta 37,5 mg/325 mg", inUse: nil, medicine_instruction_id: 58},
  {medicineNumber: "012114", name: "Tramal 150 mg tbl", inUse: nil, medicine_instruction_id: 59},
  {medicineNumber: "012084", name: "Tadol 100 mg tbl s podaljsanim sproscanjem", inUse: nil, medicine_instruction_id: 60},
  {medicineNumber: "145499", name: "Tramadol Vitabalans 50 mg tbl", inUse: nil, medicine_instruction_id: 61},
  {medicineNumber: "124680", name: "Zaracet 37,5 mg/325 mg tbl", inUse: nil, medicine_instruction_id: 62},
  {medicineNumber: "020583", name: "Flonidan 10 mg", inUse: nil, medicine_instruction_id: 63},
  {medicineNumber: "062987", name: "Claritine S 10 mg tbl", inUse: nil, medicine_instruction_id: 64},
  {medicineNumber: "051420", name: "Florgan 10 mg orodisperzibilne tbl", inUse: nil, medicine_instruction_id: 65},
  {medicineNumber: "058238", name: "Rinolan 10 mg tablete", inUse: nil, medicine_instruction_id: 66},
  {medicineNumber: nil, name: nil, inUse: nil, medicine_instruction_id: 67},
  {medicineNumber: nil, name: nil, inUse: nil, medicine_instruction_id: 68},
  {medicineNumber: nil, name: nil, inUse: nil, medicine_instruction_id: 69}
])
MedicineCheck.create!([
  {medicine_id: 1, check_up_id: 1},
  {medicine_id: 2, check_up_id: 1}
])
MedicineInstruction.create!([
  {deleted: false, url_string: "http://www.vitabalans.com/index.php?id=zopitin0004"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/F2D46D0FDF63B711C12579C2003F5E1A/$File/a-016418.pdf"},
  {deleted: false, url_string: "http://www.krka.si/sl/zdravila-in-izdelki/zdravila-na-recept/enap/1323/#title"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/68FDAEEE845A0E52C12579C2003F563B/$File/a-016414.pdf"},
  {deleted: false, url_string: "http://si.draagle.com/#!/drug/kzk/?sub=10"},
  {deleted: false, url_string: "http://www.lek.si/si/zdravila/na-recept/pakiranje/5862/"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/C393D32B6CCD5421C12579EC00200928/$File/a-009508.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/65930B0D5833253BC1257C780004AF95/$File/a-013730.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/73A663A39EB07033C12579C2003F5EE2/$File/a-014615.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/06C4EB4CE17A2068C1257C780004B023/$File/a-013839.pdf"},
  {deleted: false, url_string: "http://www.medis.si/fileadmin/medis/medis.si/docs/Navodilo_za_uporabo_Aglurab_SI.pdf"},
  {deleted: false, url_string: "http://si.draagle.com/#!/greader/?file=http%3A%2F%2Fskrito.draagle.com%2Fmedia%2Fd%2Fpil%2F040886_pil.pdf"},
  {deleted: false, url_string: "https://mediately.co/si/drugs/WjSUunNJrYrsXmP7DiMg2FANnb9/belformin-500-mg-filmsko-oblozene-tablete"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/C35AF3CC02742C17C12579EC0020018C/$File/a-007344.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/2482BE471CABFF87C12579C2003F5360/$File/a-015772.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/4FC2A54BA1DBA6A0C12579C2003F6956/$File/a-020018.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/1D5A54DC62638DE6C12579C2003F61CD/$File/a-014628.pdf"},
  {deleted: false, url_string: "https://www.diagnosia.com/si/zdravila/actrapid-100-ieml-raztopina-za-injiciranje-v-viali"},
  {deleted: false, url_string: "https://www.diagnosia.com/si/zdravila/actrapid-flexpen-100-ieml-raztopina-za-injiciranje-v-napolnjenem-injekcijskem-peresniku"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/5536585C91748BDFC12579C2003F5D63/$File/a-012384.pdf"},
  {deleted: false, url_string: "https://myhealthbox.eu/fr/view/1697664/a841ce6cfa958e9d21d2636b18e07e8c/leaflet"},
  {deleted: false, url_string: "http://www.diagnosia.com/si/zdravila/mixtard-30-novolet-100-ieml-suspenzija-za-injiciranje-v-napolnjenem-injekcijskem-peresniku"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/C3E218A9243FF5E9C1257C310004BB75?opendocument"},
  {deleted: false, url_string: "http://www.lek.si/si/zdravila/brez-recepta/ranital-s-150/"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/017078003F4E9B32C1257CC90083116E/$File/a-014247.pdf"},
  {deleted: false, url_string: "http://data.zdravila.net/pdf/a-010513.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/7C3C54F51BD29C59C12579C2003F63EF?opendocument"},
  {deleted: false, url_string: "http://si.draagle.com/#!/greader/?file=http%3A%2F%2Fskrito.draagle.com%2Fmedia%2Fd%2Fpil%2F105864_pil.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/374B2D55A7D6E43AC12579EC002008A5/$File/a-016035.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/CD18459F93237B13C12579C2003F68AF/$File/a-015652.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/B940B7C0F083BE58C12579C2003F637A/$File/a-015072.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/3291459E7EB4AD14C1257CB400833420?opendocument"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/2ABD62F024313965C12579C2003F5CBB/$File/a-012092.pdf"},
  {deleted: false, url_string: "http://si.draagle.com/#!/source/ljn/?drug=ljo"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/6151BEF7B09CA95AC12579C2003F5062?opendocument"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/44DDA83404E35C16C12579C2003F533A/$File/a-015920.pdf"},
  {deleted: false, url_string: "http://www.lek.si/si/zdravila/na-recept/pakiranje/1692/"},
  {deleted: false, url_string: "http://www.lek.si/si/zdravila/na-recept/pakiranje/433/"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/F52A113BA34EB9E3C12579EC00200024?opendocument"},
  {deleted: false, url_string: "http://www.krka.si/sl/zdravila-in-izdelki/zdravila-na-recept/sorvastatablete/1673/"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/EBA7391D45C8FEBDC12579EC0020021A/$File/a-014601.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/A2118DFEC432DB52C12579EC00200204/$File/a-016289.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/1B374BA216FAD256C12579C2003F6932?opendocument"},
  {deleted: false, url_string: "http://www.lek.si/si/zdravila/brez-recepta/lekadol-filmsko-oblozene-tablete/"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/74B2434C07A44F18C12579C2003F4B3E/$File/a-011568.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/8BA9838F72FB4FA4C12579EC001FFABB?opendocument"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/4D14143C7F6E1F04C1257C620004CDD8/$File/a-016095.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/97D3848355D4ABDAC12579C2003F5CDE/$File/a-015216.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/C8122F0572FA7141C12579EC001FFF17/$File/a-600695.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/FCD99A29EDCF611EC12579F900492129/$File/a-016002.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/5C58B200098CB5A2C12579C2003F53E1?opendocument"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/1AF7CA6F1A775F6BC12579C2003F53C6/$File/a-015373.pdf"},
  {deleted: false, url_string: "http://www.krka.si/sl/zdravila-in-izdelki/zdravila-na-recept/apaurintablete/1287/"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/0049AAE59E3AA8D3C12579C2003F532C?opendocument"},
  {deleted: false, url_string: "http://www.lek.si/si/zdravila/na-recept/pakiranje/5775/"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/8911B2FE3FFF0EF2C12579EC001FF931/$File/a-016214.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/A9B3E333AEC06FBEC12579EC001FFC93/$File/a-016422.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/C0CAA315ECDB0887C1257CC90083113C/$File/a-016017.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/011783EE948D7D8FC12579EC00200501/$File/a-016059.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/90DBE9EE574E4B0BC12579EC00200012/$File/a-016440.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/8BA9838F72FB4FA4C12579EC001FFABB?opendocument"},
  {deleted: false, url_string: "http://www.zdravila.net/navodilo.php?navodilo=s-005819.pdf&d"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/63B2B4273D302F22C12579C2003F4E25/$File/a-016266.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/031488B8CE92CA7AC1257BAC0083438E/$File/a-014109.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/871247132BF7287FC12579EC0020072B/$File/a-011732.pdf"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/85571397365F09F1C12579EC001FF803?opendocument"},
  {deleted: false, url_string: "http://www.lekarnar.com/izdelki/claritine-s-tablete"},
  {deleted: false, url_string: "http://www.cbz.si/cbz/bazazdr2.nsf/o/DA55403BA60DE053C12579EC001FF806/$File/a-013832.pdf"},
  {deleted: false, url_string: "https://www.lekarna24ur.com/public/upload/dokumenti/Rinolan_navodilo_pdf.pdf"},
  {deleted: false, url_string: "http://www.lekarnar.com/izdelki/claritine-s-tablete"}
])
PartMeasurement.create!([
  {name: "glucose", unit: "mmol/l", measurement_id: 1, value: "5.0", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 2, value: "6.0", deleted: false},
  {name: "diastolic", unit: "mmHg", measurement_id: 1, value: "70.0", deleted: false},
  {name: "diastolic", unit: "mmHg", measurement_id: 2, value: "75.0", deleted: false},
  {name: "systolic", unit: "mmHg", measurement_id: 1, value: "120.0", deleted: false},
  {name: "systolic", unit: "mmHg", measurement_id: 2, value: "125.0", deleted: false},
  {name: "HB", unit: "BPM", measurement_id: 1, value: "80.0", deleted: false},
  {name: "HB", unit: "BPM", measurement_id: 2, value: "83.0", deleted: false},
  {name: "temperature", unit: "°C", measurement_id: 1, value: "37.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 1, value: "60.0", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 3, value: "5.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 3, value: "65.0", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 4, value: "4.19", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 5, value: "4.86", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 6, value: "4.47", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 7, value: "4.49", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 8, value: "5.0", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 9, value: "4.38", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 10, value: "5.71", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 11, value: "4.52", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 12, value: "5.48", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 13, value: "4.7", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 14, value: "5.54", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 15, value: "4.15", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 16, value: "4.58", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 17, value: "4.68", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 18, value: "5.27", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 19, value: "5.63", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 20, value: "4.08", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 21, value: "5.35", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 22, value: "5.03", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 23, value: "5.71", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 24, value: "5.61", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 25, value: "4.64", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 26, value: "5.33", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 27, value: "5.13", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 28, value: "5.68", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 29, value: "4.8", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 30, value: "4.55", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 31, value: "5.19", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 32, value: "5.31", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 33, value: "5.33", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 34, value: "5.38", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 35, value: "4.57", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 36, value: "4.38", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 37, value: "5.65", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 38, value: "5.01", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 39, value: "4.09", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 40, value: "4.54", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 41, value: "5.41", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 42, value: "5.85", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 43, value: "5.07", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 44, value: "5.0", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 45, value: "4.75", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 46, value: "4.13", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 47, value: "4.28", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 48, value: "4.33", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 49, value: "5.9", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 50, value: "5.59", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 51, value: "5.94", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 52, value: "5.49", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 53, value: "4.27", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 54, value: "5.57", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 55, value: "4.93", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 56, value: "5.09", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 57, value: "4.42", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 58, value: "4.61", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 59, value: "4.12", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 60, value: "5.09", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 61, value: "4.76", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 62, value: "4.85", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 63, value: "5.84", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 64, value: "4.66", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 65, value: "4.62", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 66, value: "5.98", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 67, value: "5.29", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 68, value: "5.41", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 69, value: "5.92", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 70, value: "5.36", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 71, value: "4.74", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 72, value: "5.36", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 73, value: "4.72", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 74, value: "5.94", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 75, value: "5.17", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 76, value: "4.38", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 77, value: "4.19", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 78, value: "4.91", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 79, value: "5.07", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 80, value: "5.25", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 81, value: "5.39", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 82, value: "4.81", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 83, value: "4.81", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 84, value: "4.8", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 85, value: "4.11", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 86, value: "5.36", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 87, value: "5.27", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 88, value: "4.62", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 89, value: "5.57", deleted: false},
  {name: "glucose", unit: "mmol/l", measurement_id: 90, value: "5.94", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 1, value: "70.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 2, value: "70.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 3, value: "70.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 4, value: "70.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 5, value: "70.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 6, value: "70.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 7, value: "70.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 8, value: "70.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 9, value: "70.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 10, value: "70.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 11, value: "71.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 12, value: "71.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 13, value: "71.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 14, value: "71.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 15, value: "71.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 16, value: "71.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 17, value: "71.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 18, value: "71.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 19, value: "71.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 20, value: "71.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 21, value: "72.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 22, value: "72.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 23, value: "72.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 24, value: "72.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 25, value: "72.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 26, value: "72.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 27, value: "72.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 28, value: "72.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 29, value: "72.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 30, value: "72.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 31, value: "73.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 32, value: "73.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 33, value: "73.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 34, value: "73.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 35, value: "73.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 36, value: "73.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 37, value: "73.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 38, value: "73.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 39, value: "73.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 40, value: "73.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 41, value: "74.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 42, value: "74.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 43, value: "74.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 44, value: "74.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 45, value: "74.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 46, value: "74.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 47, value: "74.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 48, value: "74.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 49, value: "74.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 50, value: "74.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 51, value: "75.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 52, value: "75.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 53, value: "75.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 54, value: "75.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 55, value: "75.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 56, value: "75.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 57, value: "75.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 58, value: "75.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 59, value: "75.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 60, value: "75.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 61, value: "76.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 62, value: "76.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 63, value: "76.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 64, value: "76.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 65, value: "76.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 66, value: "76.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 67, value: "76.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 68, value: "76.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 69, value: "76.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 70, value: "76.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 71, value: "77.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 72, value: "77.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 73, value: "77.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 74, value: "77.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 75, value: "77.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 76, value: "77.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 77, value: "77.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 78, value: "77.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 79, value: "77.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 80, value: "77.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 81, value: "78.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 82, value: "78.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 83, value: "78.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 84, value: "78.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 85, value: "78.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 86, value: "78.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 87, value: "78.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 88, value: "78.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 89, value: "78.8", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 90, value: "78.9", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 91, value: "79.0", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 92, value: "79.1", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 93, value: "79.2", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 94, value: "79.3", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 95, value: "79.4", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 96, value: "79.5", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 97, value: "79.6", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 98, value: "79.7", deleted: false},
  {name: "weight", unit: "kg", measurement_id: 99, value: "79.8", deleted: false}
])
Patient.create!([
  {cardNumber: "01245951", lastName: "Strmljan", firstName: "Jure", phone: "123456789", birthDate: "2011-08-03", sex: "M", user_id: 2, address_id: 1, deleted: false},
  {cardNumber: "21325446", lastName: "Lusina", firstName: "Domen", phone: "041 238 983", birthDate: "2011-04-04", sex: "M", user_id: 2, address_id: 2, deleted: false}
])
Post.create!([
  {postName: "Kresnice", postNumber: "1281"},
  {postName: "Ljubljana", postNumber: "1000"},
  {postName: "Jesenice", postNumber: "4270"},
  {postName: "Medvode", postNumber: "1215"},
  {postName: "Izola - Isola", postNumber: "6310"},
  {postName: "Logatec", postNumber: "1370"},
  {postName: "Cerkno 404", postNumber: "5282"},
  {postName: "Kocevje", postNumber: "1330"},
  {postName: "Ptuj 127\"", postNumber: "2250"},
  {postName: "Velenje", postNumber: "3320"},
  {postName: "Ajdovscina", postNumber: "5270"}
])
